const Words = [
  "Let's Play",
  "I'm a newbie",
  "Apples",
  "Apricots",
  "Avocados",
  "Bananas",
  "I'm good at this",
  "Boysenberries",
  "Hello",
  "Hey!",
  "Blueberries",
  "Bing Cherry",
  "Google",
  "Cherries",
  "Cantaloupe",
  "Crab apples",
  "Clementine",
  "Google",
  "Twitch",
  "Youtube",
  "Cucumbers",
  "Damson plum",
  "Dinosaur Eggs",
  "Jackhammer",
  "The Office",
  "Dates",
  "Dewberries",
  "You Lose",
  "Dragon Fruit",
  "Elderberry",
  "Eggfruit",
  "Evergreen Huckleberry",
  "Entawak",
  "Fig",
  "Farkleberry",
  "Finger Lime",
  "Grapefruit",
  "Grapes",
  "Gooseberries",
  "Guava",
  "Honeydew Melon",
  "Hackberry",
  "Honeycrisp Apples",
  "Indian Prune",
  "Indonesian Lime",
  "Imbe",
  "Indian Fig",
  "Jackfruit",
  "Java Apple",
  "Jambolan",
  "Kiwi",
  "Kaffir Lime",
  "Kumquat",
  "Lemon",
  "Kanye West",
  "Drake",
  "Longan",
  "Avengers",
  "Lychee",
  "Loquat",
  "Mango",
  "Mandarin Orange",
  "Mulberry",
  "Melon",
  "Nectarine",
  "Navel Orange",
  "Nashi Pear",
  "Olive",
  "Oranges",
  "Ogeechee Limes",
  "Oval Kumquat",
  "Papaya",
  "Persimmon",
  "Paw Paw",
  "Prickly Pear",
  "Peach",
  "Pomegranate",
  "Pineapple",
  "Quince",
  "Queen Anne Cherry",
  "Quararibea Cordata",
  "Chupa Chupa",
  "Oompa Loompa",
  "Rambutan",
  "Raspberries",
  "Rose Hips",
  "Star Fruit",
  "Strawberries",
  "Sugar Baby Watermelon",
  "Tomato",
  "Tangerine",
  "Tamarind",
  "Tart Cherries",
  "Ugli Fruit",
  "Ugni",
  "Vanilla Bean",
  "Velvet Pink Banana",
  "Voavanga",
  "Watermelon",
  "Wolfberry",
  "White Mulberry",
  "Xigua",
  "Ximenia Caffra Fruit",
  "Xango Mangosteen Fruit Juice",
  "Yellow Passion Fruit",
  "Yunnan Hackberry",
  "Yangmei",
  "Zig Zag Vine Fruit",
  "Zinfandel Grapes",
  "Zuchinni",
  "Red",
  "Blue",
  "Yellow"
];

export default Words;